---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-solr-cloud
    image: ami-9887c6e7
    platform: centos7
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - zookeeper

  - name: test-aws-ubuntu18-solr-cloud
    image: ami-012fd5eb46f56731f
    platform: ubuntu18
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - zookeeper

  - name: test-aws-Debian9-solr-cloud
    image: ami-003f19e0e687de1cd
    platform: debian9
    instance_type: m5a.large
    region: us-east-1
    vpc_subnet_id: subnet-0f2b9cd66faea38af
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - zookeeper

  - name: test-aws-windows2016-solr-cloud
    image: ami-00a20f508263efd30
    platform: windows2016core
    aws_region: us-east-1
    instance_type: m5a.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-01be2149
    groups:
      - windows
      - solr

  - name: test-aws-windows2019-solr-cloud
    image: ami-0477b9335a5a75438
    platform: windows2019core
    aws_region: us-east-1
    instance_type: m5a.large
    assign_public_ip: true
    spot_price: 0.14
    aws_sec_group:
      - default
    vpc_subnet_id: subnet-01be2149
    groups:
      - windows
      - solr

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      all:
        solr_version: 8.0.0
      windows:
        ansible_connection: winrm
        ansible_password: "{{ lookup('env', 'WINRM_ADMIN_PWD') | default('M0leCule123!', true) }}"
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
  playbooks:
      create: ../resources/common_create.yml
      prepare: ../resources/prepare.yml
      destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-windows
verifier:
  name: inspec
  directory: ../resources/tests/

