---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-aws-centos7-solr-cloud
    image: ami-9887c6e7
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: centos
    groups:
      - rhel_family
      - zookeeper
      - solr

  - name: test-aws-ubuntu16-solr-cloud
    image: ami-09677e0a6b14905b0
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - zookeeper
      - solr

  - name: test-aws-ubuntu18-solr-cloud
    image: ami-012fd5eb46f56731f
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    security_group_name:
      - default
    spot_price: 0.04
    wait_timeout: 1800
    ssh_user: ubuntu
    groups:
      - debian_family
      - solr

  - name: test-aws-Debian9-solr-cloud
    image: ami-003f19e0e687de1cd
    instance_type: m5.large
    region: us-east-1
    vpc_subnet_id: subnet-05a2ef2b767afec50
    assign_public_ip: false
    spot_price: 0.04
    security_group_name:
      - default
    wait_timeout: 1800
    ssh_user: admin
    groups:
      - debian_family
      - zookeeper
      - solr

provisioner:
  name: ansible
  log: false
  inventory:
    group_vars:
      all:
        solr_version: 8.0.0
  playbooks:
    create: ../resources/provisioning/AWS/create.yml
    prepare: ../resources/prepare.yml
    destroy: ../resources/provisioning/AWS/destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: cloud-aws-direct
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
