---
- name: Prepare Ubuntu / Debian
  hosts: debian_family
  gather_facts: false
  tasks:

    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt install -y python-minimal)
      become: true
      changed_when: false
      register: update_result
      retries: 10
      delay: 5
      until: update_result.rc == 0

- name: Prepare RHEL
  hosts: rhel_family
  gather_facts: false
  tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (yum install -y python2 python-simplejson)
      become: true
      changed_when: false

    - name: gather facts
      setup:

    - name: 'Enable EPEL repository'
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
          {{ ansible_distribution_major_version }}.noarch.rpm"
        state: 'present'
      register: status
      until: status is succeeded
      become: true

- name: Prepare java
  hosts: all
  roles:
    - role: lean_delivery.java

- name: Prepare Zookeeper
  hosts: zookeeper
  roles:
    - role: lean_delivery.zookeeper

- name: Install and Configure Solr
  hosts: solr
  roles:
   - role: lean_delivery.solr_standalone
  vars:
    solr_change_default_password: false
    solr_auth_configure: false
    solr_use_java_version_8: false
    solr_ssl_configure: false
    solr_ssl_check_peer_name: 'false'
