---
- name: restart Solr Linux
  systemd:
    name: '{{ solr_service_name }}'
    state: restarted
  become: true
  when:
  - solr_service_start

- name: restart Solr Windows
  win_service:
    name: '{{ solr_service_name }}'
    state: restarted
