---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
platforms:
  - name: test-docker-centos7-solr-cloud-1
    image: leandelivery/docker-systemd:centos7
    privileged: true
    groups:
      - rhel_family
      - zookeeper
      - solr
  - name: test-docker-centos7-solr-cloud-2
    image: leandelivery/docker-systemd:centos7
    privileged: true
    groups:
      - rhel_family
      - zookeeper
      - solr
  - name: test-docker-ubuntu1804-solr-cloud
    image: leandelivery/docker-systemd:ubuntu-18.04
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    groups:
      - debian_family
      - zookeeper
      - solr
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_whitelist: profile_tasks,timer
  inventory:
    group_vars:
      all:
        solr_version: 8.0.0
  playbooks:
    prepare: ../resources/prepare.yml
    verify: ../resources/tests/verify.yml
scenario:
  name: default
verifier:
  name: ansible
  lint:
    name: ansible-lint
