---
- name: Force gathering facts
  hosts: all
  gather_facts: true
  roles: []

- name: Configure Solr Cloud
  hosts: solr
  roles:
    - role: ansible-role-solr-cloud
      zk_inventory_group: zookeeper
      auto_populate_configset_list: true
      zk_enable_ssl: false
